GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}
###
DELETE http://localhost:3001/todo/delete/63853ed41bb3bef838fc2be8

###
PUT http://localhost:3001/todo/complete/63853dd01bb3bef838fc2be6